<dl>
    <dt>Module:</dt>
    <dd>ZfMongoDbOdmSample</dd>
    <dt>Controller:</dt>
    <dd>DocumentManagerController</dd>
    <dt>Action:</dt>
    <dd>index</dd>
    <dt>$greeting:</dt>
    <dd><?php echo htmlentities(get_class($greeting)); ?></dd>
    <dt>$greeting->getId()</dt>
    <dd><?php echo htmlentities($greeting->getId()); ?></dd>
    <dt>$greeting->getContent()</dt>
    <dd><?php echo htmlentities($greeting->getContent()); ?></dd>
</dl>